### ISSUE TITLE
Error: Cannot find module 'irc-framework'

### ISSUE THREAD

**Issue by haxxus** [Geo1088/irc-discord#1]
module.js:471
    throw err;
    ^

Error: Cannot find module 'irc-framework'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/irc-discord/index.js:1:75)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by eritbh** [comment]
Try `npm i` or `yarn`? It's included in the `package.json` so the dependencies should work fine...

Also wew someone else is using this? Time to make it work properly and make setup functionality I guess...

**Comment by haxxus** [comment]
npm i:


[root@vultr irc-discord]# sudo npm install
npm WARN less-shitty-irc@0.0.0 No repository field.

**Comment by eritbh** [comment]
That looks like the correct output. This is a project that I pretty much just started on, so things like the package.json will likely be incomplete. The deps should be there but consider most of this repo WIP for now.
